# Generated by Django 4.2.20 on 2025-04-22 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=50, unique=True)),
                ('genre', models.CharField(choices=[('Please Select', 'PLEASE SELECT'), ('Pop', 'POP'), ('Rock', 'ROCK'), ('Blues', 'BLUES'), ('Jazz', 'JAZZ'), ('Fusion', 'FUSION')], default='Please select')),
                ('slug', models.SlugField(unique=True)),
                ('review', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
