# Generated by Django 4.2.20 on 2025-04-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='number_of_members',
            field=models.CharField(choices=[('Please Select', 'PLEASE SELECT'), ('Solo artist', 'SOLO ARTIST'), ('Two', 'TWO'), ('Three', 'THREE'), ('Four', 'FOUR'), ('Five', 'FIVE'), ('Six', 'SIX'), ('Seven or more', 'SEVEN OR MORE')], default='Please select'),
        ),
    ]
