# Generated by Django 4.2.20 on 2025-04-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_band_number_of_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AddField(
            model_name='band',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('Please Select', 'Please Select'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Blues', 'Blues'), ('Jazz', 'Jazz'), ('Fusion', 'Fusion')], default='Please select'),
        ),
        migrations.AlterField(
            model_name='band',
            name='number_of_members',
            field=models.CharField(choices=[('Please Select', 'Please Select'), ('Solo artist', 'Solo artist'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven or more', 'Seven or more')], default='Please select'),
        ),
    ]
