# Generated by Django 4.2.20 on 2025-04-23 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bands', '0003_band_status_band_updated_on_alter_band_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('Please Select', 'Please Select'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Please select')),
                ('again', models.CharField(choices=[('Please Select', 'Please Select'), ('yes', 'yes'), ('no', 'no'), ('maybe', 'maybe')], default='Please select')),
                ('your_opinion', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinionator', to=settings.AUTH_USER_MODEL)),
                ('band_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='bands.band')),
            ],
        ),
    ]
