# Generated by Django 4.2.20 on 2025-04-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='rating',
            field=models.CharField(choices=[('Please Select', 'Please Select'), ('very bad', 'very bad'), ('bad', 'bad'), ('average', 'average'), ('good', 'good'), ('very good', 'very good')], default='Please select'),
        ),
    ]
