# Generated by Django 4.2.20 on 2025-04-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_alter_opinion_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='opinion',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='band',
            name='review_excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='your_opinion_excerpt',
            field=models.TextField(blank=True),
        ),
    ]
