# Generated by Django 4.2.20 on 2025-05-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0009_alter_band_number_of_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('Please Select', 'Please Select'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Metal', 'Metal'), ('Punk', 'Punk'), ('Blues', 'Blues'), ('Jazz', 'Jazz'), ('Fusion', 'Fusion')], default='Please select'),
        ),
    ]
