# Generated by Django 4.2.20 on 2025-05-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0010_alter_band_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='please_rate_the_band',
            field=models.CharField(choices=[('', ''), ('very bad', 'very bad'), ('bad', 'bad'), ('average', 'average'), ('good', 'good'), ('very good', 'very good')], default=''),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='would_you_see_this_band_again',
            field=models.CharField(choices=[('', ''), ('yes', 'yes'), ('no', 'no'), ('maybe', 'maybe')], default=''),
        ),
    ]
