# Generated by Django 4.2.20 on 2025-05-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0011_alter_opinion_please_rate_the_band_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='your_opinion_excerpt',
        ),
    ]
