# Generated by Django 4.2.20 on 2025-05-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0012_remove_opinion_your_opinion_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='your_opinion',
            field=models.TextField(max_length=5),
        ),
    ]
