# Generated by Django 4.2.20 on 2025-05-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0014_alter_band_review_alter_opinion_your_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='review',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='your_opinion',
            field=models.TextField(max_length=3000),
        ),
    ]
