# Generated by Django 4.2.20 on 2025-04-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_band_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('tell_us_about_your_band', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
