# Generated by Django 4.2.20 on 2025-04-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_collaboraterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboraterequest',
            name='your_name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='your_band_name',
            field=models.CharField(max_length=50),
        ),
    ]
