# Generated by Django 4.2.20 on 2025-04-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0003_collaboraterequest_your_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboraterequest',
            name='your_name',
            field=models.CharField(max_length=50),
        ),
    ]
