# Generated by Django 4.2.20 on 2025-04-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0004_alter_collaboraterequest_your_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboraterequest',
            name='genre',
            field=models.CharField(choices=[('Please Select', 'Please Select'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Blues', 'Blues'), ('Jazz', 'Jazz'), ('Fusion', 'Fusion')], default='Please select'),
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='number_of_members',
            field=models.CharField(choices=[('Please Select', 'Please Select'), ('Solo artist', 'Solo artist'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven or more', 'Seven or more')], default='Please select'),
        ),
    ]
