# Generated by Django 4.2.20 on 2025-05-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0005_collaboraterequest_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboraterequest',
            name='genre',
            field=models.CharField(choices=[('', ''), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Blues', 'Blues'), ('Jazz', 'Jazz'), ('Fusion', 'Fusion')], default=''),
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='number_of_members',
            field=models.CharField(choices=[('', ''), ('Solo artist', 'Solo artist'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven or more', 'Seven or more')], default=''),
        ),
    ]
