# Generated by Django 4.2.20 on 2025-05-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0006_alter_collaboraterequest_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='updated_on',
        ),
    ]
