# Generated by Django 4.2.20 on 2025-05-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0007_remove_about_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_us',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='tell_us_about_your_band',
            field=models.TextField(max_length=250),
        ),
    ]
