# Generated by Django 4.2.20 on 2025-05-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0008_alter_about_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_us',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='tell_us_about_your_band',
            field=models.TextField(max_length=3000),
        ),
    ]
