# Generated by Django 4.2.20 on 2025-05-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0009_alter_about_about_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='collaboraterequest',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='collaboraterequest',
            name='number_of_members',
        ),
    ]
